### ISSUE TITLE
Install location of cdist-conf

### ISSUE THREAD

**Issue by fancsali** [cdist-community/cdist#3]
The installation howto both instructs you to make sure, the submodule is checked out under `cdist-core/conf`, and then suggests you check out the `cdist-conf` repo separately.

On one hand, if we want to have the core code and the types (essential, extra, or otherwise) we should completely separate them.

Then again the core types are expected to be part of the default install, so probably one should not check them out again.

So, probably the docs need to be updated, so the `cdist-conf` essential repo is always understood to be already there.

**Comment by sideeffect42** [comment]
The current situation of cdist-conf is suboptimal.

In the end I think cdist-core should provide a method to install and upgrade cdist-conf (and possibly also other "sets" like cdist-extra) via a special command or something.

Until that is implemented, we "hacked" cdist-conf into cdist-core as a submodule so that you can still install cdist from Git and get a working installation with core types as you would've with cdist-ungleich.

The the Getting Started there are two procedures:
"Get core with essentials" does just this. It installs from the core repo.
"Get everything" installs all repos separately.

You should only do one of the two, not both. Maybe we should specify this more clearly?

**Comment by fancsali** [comment]
I've been thinking about this over the weekend. Let me share the points, I've been contemplating.

1. Surely in the long run we're looking at packaging this project, and letting people just do `apt install`/`yum install`/`dnf install`/`zypper install` or `pip install` to get the things up and running.
2. A reasonable person would then expect, the core packages are available with a minimal install (as above); so the application package either contains or depends on the core types.
3. I envision further type sets being provided as optional packages or installed by the user manually
4. The "official" extra types would be installed in known locations, so probably it'd be nice to have a default search path that would find those too. However, this would require to either hard-code all the potential locations in the base package; or to extend the Python code with a "scan" logic for types with wildcards. (As opposed to a list of user-provided paths)
5. This last point could then help with manually installed third party packages: Users would have their project in git, and create a subdirectory (let's say `third-party-types`) and add other people's type repos as submodules. Then just say `CDIST_PATH=./third-party-types/*`.
6. To keep things clean, it'd be probably wise, to introduce a policy for the non-core types (type packages) to only depend on the core ones and not on other third party packages.

As for now, we can get away with re-wording the README, though...

**Comment by 4nd3r** [comment]
IMHO we should drop submodules and just recommend doing "get everything".
